### ISSUE TITLE
Feature Request: Update to SwiftUI and RealityKit

### ISSUE THREAD

**Issue by derwaldgeist** [shu223/ARKit-Sampler#13]
Thanks a lot for these samples, they are really helpful. It would be super nice if there was an updated version available which uses SwiftUI and RealityKit (ARView). There are not many good examples out there that show all of these features in a comprehensible way.

**Comment by derwaldgeist** [comment]
Update: Just found this repo:
https://github.com/john-rocky/RealityKit-Sampler

**Comment by shu223** [comment]
Thanks! Also here is visionOS-Sampler which uses SwiftUI and RealityKit:
https://github.com/shu223/visionOS-Sampler
